# Generated by Django 2.1.1 on 2018-10-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=65)),
                ('esal', models.IntegerField()),
                ('eadd', models.CharField(max_length=65)),
            ],
        ),
    ]
