# Generated by Django 2.1.1 on 2018-10-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custmor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(max_length=65)),
                ('custadhornumber', models.IntegerField()),
                ('custemail', models.CharField(max_length=20)),
                ('custphonenumber', models.IntegerField()),
                ('custage', models.IntegerField()),
            ],
        ),
    ]
